---
######## IMPORTANT: TO TEST I REMOVED THE CREATION OF THE BACKEND DIRECTORY _ IN PRODUCTION IT HAS TO BE BACK ######

# - name: create the directory
#   shell: mkdir backend
# - name: Copy zipped, compiled backend
#   template:
#     src: '~/project/artifact.tar.gz'
#     dest: '/home/ubuntu/backend'
# - name: Copy index test page
#   template:
#     src: '~/project/test.txt'
#     dest: '~/'
# - name: seeing if the script runs
#   shell: |
#     cd ~~
#     touch hallo.txt
#run
- name: download the zipped artifact
  shell: |
    cd backend
    curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jmpberlin/cdond-c3-projectstarter/$CIRCLE_BUILD_NUM/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
  # curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jmpberlin/cdond-c3-projectstarter/latest/artifacts

- name: 'update apt packages.'
  become: yes
  apt:
    update_cache: yes

- name: 'upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
- name: 'install dependencies'
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
########## sudo apt install pm2 doesnt work out of the box #######
########## alternatively I'll do the following:
- name: 'install pm2 manually'
  shell: |
    sudo npm install pm2 -g
    cd ~/
