---
- name: print all env vars
  shell: |
    printenv
- name: test env vars
  shell: |
    echo $CIRCLE_TOKEN
- name: download the zipped artifact
  shell: |
    cd backend
    curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jmpberlin/cdond-c3-projectstarter/$CIRCLE_BUILD_NUM/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -

- name: 'update apt packages.'
  become: yes
  apt:
    update_cache: yes

- name: 'upgrade packages'
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
- name: 'install dependencies'
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: 'install pm2 manually'
  shell: |
    sudo npm install pm2 -g
    cd ~/
