---
- name: print all env vars
  shell: |
    printenv
- name: test env vars
  shell: |
    echo $CIRCLE_TOKEN
- name: start the script
  shell: |
    cd backend/
    npm install
    pm2 stop npm
    pm2 start npm -- start
